### ISSUE TITLE
Copy button has larger padding than the rest of the buttons

### ISSUE THREAD

**Issue by Dannomac1** [manzinello/mailgo#101]
Hello,
I noticed the copy button has a much larger padding than the rest of the buttons. I am not sure if this is intentional but I thought I would report it just in case it wasn't.

**Comment by manzinello** [comment]
It is intentional! The very first idea of mailgo was only to copy the email address, then all the actions has been added.

Thank you anyway for your report. I close it at the moment, if someone else find this choice not so good or useful we can talk about a new design about the buttons.
