### ISSUE TITLE
Custom actions?

### ISSUE THREAD

**Issue by homotechsual** [manzinello/mailgo#104]
Is it possible for us to pass a link to MailGo as an option and have it rendered as a custom action? 

For example, in the [CiviCRM integration](https://civicrm.org/extensions/commlink) it would be beneficial if we could replicate a core function when we override email links. That core function lets us create a CRM "activity" when clicking on an email. If we could add an "Open activity" action - we'd replicate the current status quo and add the amazing additional options provided by MailGo :-)

**Comment by manzinello** [comment]
I think that this will be a good enhancement, thank you for your proposal!

**Comment by gianantoniopini** [comment]
I will work on this.

**Comment by gianantoniopini** [comment]
Just would like to double check that what I have implemented so far (on my fork) would satisfy the requirements.

What I've done so far:
- new "custom" action can be enabled or disabled in the mailgo config (default is `true`, as for the other actions)
- when constructing the mailto links it is possible to provide two new attributes (`data-custom-action-text` and `data-custom-action-url`), for example: 
      `<a href="mailto:info@mailgo.dev" data-custom-action-text="Open Activity" data-custom-action-url="https://dummy-url-to-test-custom-action?param1=test&param2=123&email=info@mailgo.dev">info@mailgo.dev</a>`
- with the example mailto link specified above, when the mailgo modal opens it will also show an additional link whose text will be "Open Activity" and which, when clicked, will open a new browser tab with the url "https://dummy-url-to-test-custom-action?param1=test&param2=123&email=info@mailgo.dev"

This will only work when mailgo is used with mailto: links. So it is not supported, for now, with tel: or callto: links and with mailgo direct render.

@MikeyMJCO Would this work for you?

**Comment by homotechsual** [comment]
Absolutely :-) this is fantastic and fills the gap we had exactly :-)

**Comment by gianantoniopini** [comment]
Great, good to know! I will submit a PR so my changes can be reviewed in more detail.

**Comment by manzinello** [comment]
Thank you again for your work @gianantoniopini! I have now added a new page in the docs to specify the instructions for the custom actions. If you want to help me to write it: https://mailgo.dev/docs/custom-actions. The file is a simple markdown file and it is this one: https://github.com/manzinello/mailgo.dev/blob/master/docs/custom-actions.md. If you can't no problem, I will write it. I am proposing it to you because you have developed this functionality and maybe you want your name on mailgo.dev page as an author! Thank you again.

**Comment by gianantoniopini** [comment]
@manzinello Pleasure to be able to contribute! Yes I can help to write the docs related to custom actions. I will submit a PR with the additions to the custom-actions.md file.
