### ISSUE TITLE
Export of validateEmail function

### ISSUE THREAD

**Issue by gianantoniopini** [manzinello/mailgo#105]
It would be useful to be able to validate the To email using the same validation function used internally by mailgo.

As a consumer of the mailgo library, I would like to have the ability to validate the To email address using exactly the same validation function (i.e. same RegEx) that is used internally by mailgo. This is so that the user can be notified of an invalid To email address before the mailgoDirectRender function is called. In this way the validation of the To email address will be done in the same way by the consumer and mailgo.

Therefore it could be useful to export the mailgo validateEmail function, so that consumers of the library can use it if needed.

I would be willing to submit a PR for this.

**Comment by manzinello** [comment]
Good idea! Submit directly your PR referring to this issue, thank you.

**Comment by gianantoniopini** [comment]
@manzinello Should we also update the docs for this new function export?

**Comment by manzinello** [comment]
Yes, please! Thank you!
You can submit a PR on this page https://mailgo.dev/docs/mailgo-exports

**Comment by gianantoniopini** [comment]
OK, will do.

**Comment by gianantoniopini** [comment]
@manzinello Just noticed that the new mailgoValidateEmail function is not defined in the window element, like the other exported functions. It is something I've missed. Should I submit a PR to correct this?

**Comment by manzinello** [comment]
Submit directly PR, thank you.

**Comment by gianantoniopini** [comment]
OK, thank you.
