### ISSUE TITLE
Run unit tests automatically on each push or pull request

### ISSUE THREAD

**Issue by gianantoniopini** [manzinello/mailgo#110]
It would be nice to have the unit tests run automatically any time someone pushes commits or creates a pull request.

This could be done via a new GitHub action.

If it could be a welcome addition, I would be happy to submit a PR for this.

**Comment by manzinello** [comment]
A really good idea! Thank you so much.

**Comment by gianantoniopini** [comment]
You are welcome! I will then submit a PR for this.
