### ISSUE TITLE
to validateEmail or not to validateEmail?

### ISSUE THREAD

**Issue by manzinello** [manzinello/mailgo#17]
**validateEmail** is not present in the normal mailto links.
Mantain it in mailgo or not?

**Comment by kaknut** [comment]
I think it would be better to let it stay to keep it simple and have versatility.
Like + is used nowadays to use multiple mail, in future these might develop more.

**Comment by manzinello** [comment]
Thank you for your suggestion! At the moment mailgo performs the **validateEmail**, maybe it is the time to think about a **validateTel** too

**Comment by kaknut** [comment]
Yeah, having it as a option would be better.

**Comment by manzinello** [comment]
validateEmail and validateTel are now options in MailgoConfig! By default they are both true.
