### ISSUE TITLE
Suggestion/Discussion of Accessibility & Progressive enhancement improvements

### ISSUE THREAD

**Issue by nikolay-mihaylov** [manzinello/mailgo#18]
Hey, Matteo!
First of all, great idea, kudos!

Wouldn't it better to have the default behavior of `mailto:` in the `href` attribute and parsing the oldschool attributes with `preventDefault()` instead of using `data-attr`?

**Pros:**
- Support for noJS users;
- 100% accessible as it's using default browser functionality.

**Cons:**
- Loosing the spam protection of email partitioning with `data-attr`

I would love to hear other people opinions on this.
Have a great day!

**Comment by manzinello** [comment]
Hi Nikolay, thank you!

Actually mailgo does also this! There are more ways to enable mailgo, in the default installation (just importing the script) mailgo already intercepts the classic `mailto:` links and shows the modal (with also the optional parameters cc, bcc, subject and body). The no-spam installation are optional (but I think that it is recommended, for the spam prevention!).

Have I understand correctly the question? And if I have understood the question and answered, do you think that the documentation is not clear?

Thank you again!
Have a great day.

**Comment by nikolay-mihaylov** [comment]
Hah, sorry! Guess it was too early for me to pay attention and comment..
Everything is there. Ignore me! :)

Have a great day!

**Comment by manzinello** [comment]
No problem Nikolay! And thanks for your feedback!
