### ISSUE TITLE
📞 Add phone functionalities

### ISSUE THREAD

**Issue by hugobqd** [manzinello/mailgo#20]
Great tool, thanks !

It would be great to have the same principle for phone links.
It could sent to default link, skype, sms: …  
And spam protection.

**Comment by manzinello** [comment]
A great idea! I will do it! Thank you!

**Comment by manzinello** [comment]
WIP!

<img width="284" alt="Screenshot 2019-09-14 at 11 35 43" src="https://user-images.githubusercontent.com/5347132/64906237-3618e700-d6e4-11e9-812c-a18b22ac5dd3.png">

Suggestions for the actions to perform?

**Comment by manzinello** [comment]
In testing! Everything available in the next release!

**Comment by hugobqd** [comment]
Great ! I'll try it on the next project
