### ISSUE TITLE
MouseEvent.Path not supported in Safari

### ISSUE THREAD

**Issue by Van-Halen** [manzinello/mailgo#24]
event.path.forEach on line 283 in 0.4.9 returns:
`typeError: undefined is not an object (evaluating 'event.path.forEach')`

See:
https://stackoverflow.com/questions/36845515/mouseevent-path-equivalent-in-firefox-safari

for two possible/working solutions.

**Comment by manzinello** [comment]
thank you! I will fix it in the next release!

**Comment by Van-Halen** [comment]
composedPath() nor event.path seem to work in MS Edge.

a probable crossbrowser solution would be a custom composedPath function:
https://stackoverflow.com/a/45061945

`var path = event.path || (event.composedPath && event.composedPath()) || composedPath(event.target);
    if (path) {
      path.forEach(function (element) {`

**Comment by manzinello** [comment]
I'm trying just now with event.composedPath(), thank you for your help and testing! In the next release I will surely define custom composedPath as you say. Thank you!

**Comment by manzinello** [comment]
@Van-Halen I've released mailgo 0.4.10 just now (with all your suggestions for this issue)! Let me know if you will test it! Thank you again.
