### ISSUE TITLE
Bug with body and subject

### ISSUE THREAD

**Issue by manzinello** [manzinello/mailgo#26]
Bug of not displaying body and subject in email

**Comment by ghost** [comment]
This is still happening - when attempting to open my default email client (Outlook.exe) only the "to" field is being populated. The rest of the URL parameters are being ignored. I confirmed by testing the complete link in your example page (https://mailgo.js.org/docs/examples#complete-less-spam-mailgo-example) but it is still not working. When I use the default mailto behavior without this library, Outlook works as expected and opens the new email window with all the fields correctly populated.

Gmail works with your complete example (https://mailgo.js.org/docs/examples#complete-less-spam-mailgo-example) but I did notice whitespace being removed.

**Comment by manzinello** [comment]
Re-opened, i will work on this. Thank you.

**Comment by aminimalanimal** [comment]
Our team just ran into this today.

Taking a quick glance at mailgo.ts, it looks like subject is only appended to the URL for Yahoo and Outlook links, and not Gmail and default. @manzinello, is that all that's happening, or have you found something more complex going on? If it's as simple as it looks, I could take a stab at resolving it.

**Comment by manzinello** [comment]
Hi @aminimalanimal, in these days I am working about this. About the "default" you are right, but I have pushed just yesterday a possible fix (this commit: https://github.com/manzinello/mailgo/commit/eefcc0ea829c95f8c191a3668f0b48b6c8ad2510). However, about the Gmail it was more complex but I am testing a new solution that I have applied in this commit (https://github.com/manzinello/mailgo/commit/f87124b917ae11fdf87309ce18dfe2dbdfc098f0), some other little changes are also in the subsequent commits. All these changes are in testing at the moment, if everything works correctly everything will be in **mailgo 0.10.5** and I think that maybe I will close this issue! What do you think about? Maybe you have seen `mailgo.ts` just before these commits or your comments are referring to the latest version of `mailgo.ts`?

**Comment by aminimalanimal** [comment]
I believe I was looking at it just before your latest commits.

**Comment by manzinello** [comment]
I close this issue now, please if something is not working again re-open it!
