### ISSUE TITLE
How to add to Hugo site?

### ISSUE THREAD

**Issue by aormsby** [manzinello/mailgo#37]
Hi, I'm currently building a static site with Hugo and would like to add mailgo to my site. However, I've been unable to get it functioning. I've followed the examples on the mailgo pages by linking to the script in the head and body, even by downloading the script itself, but nothing seems to work. Has anyone tried this with a Hugo site yet? Am I missing something?

**Comment by aormsby** [comment]
I have a guess - I'm not well versed in web stuff, but perhaps a static site simply won't support this kind of thing. I'll feel very noob-ish if that's the case. Please confirm for me if you can. Thanks. 😄

**Comment by aormsby** [comment]
Never mind! I'm silly. I forgot that Hugo just updated to using Goldmark and therefore doesn't display inline HTML by default on its pages. For anyone curious how to fix this, open your site config file and add:

```
[markup.goldmark.renderer]
    unsafe = true
```
(toml version)

Then everything works fine!

**Comment by manzinello** [comment]
Hi! Installation in Hugo is ok, now? I haven't added Hugo in https://mailgo.js.org/docs/installation-in-frameworks docs, would you like to help me adding it? You can submit a PR to https://github.com/manzinello/mailgo.js.org or you can write it here and I will add it to the official docs! Thanks, have a great day

**Comment by aormsby** [comment]
Yeah, I'd love to! Contributing is fun. 👍 

I'm not having any problems now, now. It seems like mailgo works great with Hugo, but I was stuck because hadn't found that one little config parameter. It's because they just switched their default markdown handler from Blackfriday to Goldmark and the settings are set by default to skip over inline html in markdown files. So I can make a note for users to check that. After that, it turned out to be super easy to add a mailgo link into a page.

I even made a reusable shortcode for Hugo that streamlines mailgo's use a bit in a markdown file (and doesn't require that config parameter changed!).  I can add the shortcode sample as well. Or would it be better to link to a Gist of mine?

**Comment by manzinello** [comment]
Whatever you want! You can submit a PR changing this file https://github.com/manzinello/mailgo.js.org/blob/master/docs/installation-in-frameworks.md with your solution/suggestions (adding a new title like React, Angular...), if you want to create a gist you can do it and then I will link it in the same doc page! Maybe the first solution is more clear, but no problem also for the second way. The title of that page in docs is at the moment "React / Angular / Vue", but adding Hugo I will change it in "Installation in frameworks" like the url. Thanks for your help!
