### ISSUE TITLE
BUG - Problemi di compatibilità su Browser con ES5

### ISSUE THREAD

**Issue by StefanoGagliardi** [manzinello/mailgo#38]
Usando il plugin su Browser come safari o IE alcune feature javascript usate non sono supportate.
Bisognerebbe creare una dist con Babel in modo da portare la compatibilità ad ES5.

**Comment by manzinello** [comment]
Grazie mille della segnalazione! Sto giusto rivedendo in questo periodo un po' tutto il progetto che sto completamente migrando a TypeScript e dando la compatibility al SSR dando la possibilità di fare l'init dello script quando si vuole (e non solo al DOMContentLoaded di default). Interessante segnalazione questa: mi sai dire di più riguardo alle funzionalità non supportate per caso? Babel è già nel progetto e uso la browserlist ma in effetti potrebbe esserci qualcosa che non va nel procedimento di build

**Comment by StefanoGagliardi** [comment]
Seguirà una segnalazione pià accurata ci mancherebbe!

Ne aproffito per condividere un paio di idee mentre usavo il plugin:
1. Carino avere la possibilità di tradurre: i18n 
2. Possibilità di escludere alcuni social dal popup.
ES. IL numero non supporta whatsapp ci starebbe non fare il render.

Ottimo lavoro, complimenti!

**Comment by manzinello** [comment]
Entrambi i punti utili e credo che si potranno smarcare entrambi con un oggetto di config a cui sto lavorando proprio con la prossima grossa release, in cui si potranno aggiungere dettagli di configurazione sul modal e altro (sono ancora molto indietro in realtà). Ad ogni modo ho aggiunto ulteriori due issue con i tuoi consigli: #39 e #40. Credo proprio che si potranno chiudere entrambi appunto con il concetto di configurazione ma ho aperto comunque le issue separate magari per fare anche un po' di conversazione, il tema dell'i18n per esempio può essere risolto in differenti modi. Grazie mille per i consigli!

**Comment by manzinello** [comment]
Ciao Stefano, nella nuova versione di mailgo ho aggiunto l'i18n e dovrei aver fixato i problemi relativi a ES5. Ho in effetti modificato moltissime cose nel progetto (migrato a TypeScript, rimosso totalmente gulp per solo webpack e molto altro) dalla 0.9.0 che ho rilasciato ieri (con dei bug che ho fixato oggi), se ti va di fare qualche test fammi sapere! Ogni consiglio è ben accetto (anche sulle nuove funzionalità).
