### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by manzinello** [manzinello/mailgo#41]
Mailgo dark mode

**Comment by Kvanrooyen** [comment]
If no one is working on this, I would like to make a start on this.

**Comment by manzinello** [comment]
Hi, I'm already working on this (https://mailgo.dev/docs/dark-mode), but if you want to help / give some suggestion it would be awesome!

**Comment by Kvanrooyen** [comment]
Is there anything that you need help with in particular? If not I think I will start by testing what you have and seeing if I can help out that way

**Comment by manzinello** [comment]
Well a test of dark mode would be very useful! I've implemented it but not tested very well, thank you.
About the dark mode there is something that is not convincing me: the installation if mailgo is not imported in bundle but for example using a `<script>`. I want to give the possibility to use the dark mode also importing `/dist/mailgo.min.js` and so I create with webpack a `/dist/mailgo.dark.min.js`, I don't think it's a good idea. Maybe a config (attached to `window`?) is a better idea, I don't know...

**Comment by Kvanrooyen** [comment]
I've had a chance now to test a little, during this time I have noticed a few things.

1. When using dark mode, the application names are all the same colour (see screenshot for reference) whereas in the default mode, they are coloured.
![Dark Modal](https://user-images.githubusercontent.com/17731202/87566627-33e43800-c6bb-11ea-9f21-81e0cabae06c.png)
![Default Modal](https://user-images.githubusercontent.com/17731202/87566628-35156500-c6bb-11ea-89cc-bb491ede5b06.png)
2. For me the default text colour on the dark theme is a little dark and can be difficult to read for some people

> I want to give the possibility to use the dark mode also importing /dist/mailgo.min.js and so I create with webpack a /dist/mailgo.dark.min.js, I don't think it's a good idea.

I agree with this, I was thinking maybe you could use a `class` in the HTML. Something like this:
```html
<!-- Default -->
<a href="mailto:matteo@manzinello.dev,matteomanzinello@gmail.com?cc=ciao">matteo@manzinello.dev</a>
<!-- Dark -->
<a href="mailto:matteo@manzinello.dev,matteomanzinello@gmail.com?cc=ciao" class="dark">matteo@manzinello.dev</a>
```

What do you think?

**Comment by manzinello** [comment]
Thank you so much Keagan! All your suggestions/impressions are really appreciated, in particular:
1. you have right, it could be a good idea to add a colour for the dark mode actions (very light maybe), the colour now appears only on hover;
2. thank you so much, I can work on this.

About the dark mode setting I will think about it... Maybe a developer/user want to apply the dark mode to all the `mailto` links, if we use the class all the `mailto` have to be changed... I really don't know which is the best way to proceed here, maybe a combination of the solutions: if `mailto.dark.min.js` is imported all the mailgo are in dark mode, but with `mailgo.min.js` you can also specify a single (or more) dark mode mailgo? I don't know, what do you think about?

**Comment by Kvanrooyen** [comment]
I agree with you, I think a combination of the two would work best

**Comment by manzinello** [comment]
I've worked on the mixed solution (mailgo.dark.min.js or class="dark"), you can see the updated documentation here https://mailgo.dev/docs/installation#dark-mode and here also come examples https://mailgo.dev/docs/dark-mode.

I am also working on your suggestion about the colors also in dark mode!

**Comment by manzinello** [comment]
Relased **mailgo 0.9.10** with a colorful dark mode and the new dark `class`. Thank you again!

**Comment by Kvanrooyen** [comment]
I haven't had the chance to look into it yet - been incredibly busy at work lately. I should get some free time this weekend, and will give it look through. Glad I could be of some help!

**Comment by manzinello** [comment]
No problem and thank you again for your suggestions!

Here 2 screens of the new (colorful) dark mode.

<img width="293" alt="mailgo-mail-dark" src="https://user-images.githubusercontent.com/5347132/88413397-68eb3b80-cddb-11ea-983f-3aab73284fcc.png">

<img width="291" alt="mailgo-tel-dark" src="https://user-images.githubusercontent.com/5347132/88413403-6be62c00-cddb-11ea-96de-ae60738136a7.png">

Maybe I will close this issue, but if you want to give other suggestions they will be appreciated, thank you!

**Comment by Kvanrooyen** [comment]
Looks good. I think you can close this issue, if I need to I can always open it again

**Comment by manzinello** [comment]
Thank you!
