### ISSUE TITLE
A good RegEx for phone numbers

### ISSUE THREAD

**Issue by manzinello** [manzinello/mailgo#45]
I was working on `validateTel`, this is the **RegEx** I have added at the moment:

```
/^[+]*[(]{0,1}[0-9]{1,4}[)]{0,1}[-\s\./0-9]*$/
```

https://regexr.com/3c53v

It is good enough? I don't want it too restricted...

**Comment by tomma5o** [comment]
Hi @manzinello,
I've tested that regex with the most strange numbers in the world accordingly to this [Wikipedia page](https://en.wikipedia.org/wiki/National_conventions_for_writing_telephone_numbers)

That regex fails in some cases for some format numbers in South Korea, Germany, or Russia.

Normally fails with this formats: 
`8 (123) 123-22-33 `(Russia)
or
`+49 (1234) 123456`(Landline phone numbers South Korea)

Probably is better `{0,1}` for the `+` sign
and added this snippet `[\s0-9]{0,}`

```regex
^[+]{0,1}[\s0-9]{0,}[(]{0,1}[0-9]{1,4}[)]{0,1}[-\s\./0-9]*$
```

Hope this helped ;)

**Comment by manzinello** [comment]
Hi Tommaso, thank you so much for your work and your study on phone numbers.
Do you want to submit a PR with this change? I am totally agree with your proposal.
If you don't want to submit directly a PR I will substitute the RegEx in order to have it in the next release, thank you again.

**Comment by tomma5o** [comment]
I'll open a PR asap 👍
