### ISSUE TITLE
[proposal] Refactor Dom generation

### ISSUE THREAD

**Issue by tomma5o** [manzinello/mailgo#48]
Hi again @manzinello,

First of all, thanks for this lib! I really appreciate the problem you want to solve!👍
after the fork, I've looked the code and I see the DOM generation can be improved in readability 👓 

Here an example with a useful lib ([dom-chef](https://github.com/vadimdemedes/dom-chef)) that uses JSX for the DOM generation and saves you a lot of verbosities which is currently caused by vanilla JS.
<details>
  <summary>Example:</summary>
<p></p>
    <img src=https://user-images.githubusercontent.com/8134038/88343664-32151700-cd42-11ea-84ec-79a32d4ea20d.png />
</details>

If you want in my free time I can work in parallel at this feature if u like the idea

Here some pro/cons:

**PRO:**
- legibility
- less scary for newcomers

**CONS:**
- a lot of refactoring
- introduction of the JSX (not a real cons but dunno if u want to do all in vanilla ;) )

**Comment by manzinello** [comment]
Hi Tommaso, I've read everything and see more about the library `dom-chef` you have mentioned.

Well, I want to create a **discussion about this proposal**: I think that it is very good and for me and the **legibility** (and the consequence: the probability of new contributions!) is so important.
However, I want to underline a characteristic of mailgo: **zero-dependency** and the effect of zero-dependency, the **size** of the lib.

At the same time, I see that you have added the size of the library `dom-chef` and I see that it is very light and I want to think about it!

I love JSX and I work with it every day, I really want to measure the advantages of **legibility** compared to add a dependency with the consequences of the **size that automatically will grow**. What do you think about it?

Well, is there the possibility to work on legibility (maybe introducing JSX that will be so useful in this library) of the code but adding the "translation" in build phase? In this way we will avoid the dependencies not empty in package.json...

Last thing:

> a lot of refactoring

is not a **CONS**! I see in your screen that you have moved the `constants`, this is what I really want to introduce as soon as possible in mailgo!

**Comment by tomma5o** [comment]
Hi @manzinello,

Ok, I understand the **zero-deps**. 
We can do it recreating a sort of `React.createElement` function that clean some verbosity, but I think 1.6kb of **dom-chef** is the right price to pay 😄
As a newcomer is really difficult to understand what/where dom is injected and I need to follow all the _appendChild_ chain,
probably some separation of concern helps but personally I prefer the JSX way. 

As of today, we can start to clean up the code and divide it up for clearness, and if we are still not happy with the readability, we can choose the dom-chef way.

What do you think about it?

**Comment by manzinello** [comment]
> We can do it recreating a sort of React.createElement function that clean some verbosity, but I think 1.6kb of dom-chef is the right price to pay 😄

I have to think about the add a dependency really in deep. From the beginning of this library in many cases I was in trouble about this but then I have **always** chosen to use vanilla. Now I think that the source code is composed by too many lines (and a single file, I really want to change it) and in some point it must be changed in a more clear way, but the change of the **zero-dep** is completely different.

> As a newcomer is really difficult to understand what/where dom is injected and I need to follow all the appendChild chain,
> probably some separation of concern helps but personally I prefer the JSX way.

Personally I prefer the JSX way, too! I haven't applied it to this library for all the considerations already explained. I just want to think about it but also receive other suggestions about it, from other contributors or other developers. I don't want to apply a big change as the transformation from **zero-dep** to **non zero-dep** just from this fast discussion, I know that you can understand.

Well, except for the `dom-chef` I am really agree about the **cleaning up of the cose and the division in sub files of the src**, they are a great idea and something I really want to work / get help from you if you want! At the moment I think that we have to focus on it (that always make the **readability** better), you can submit directly a PR for this!

**Comment by manzinello** [comment]
I am closing some old issues, if you want you can re-open it!
