### ISSUE TITLE
Load CSS separately 

### ISSUE THREAD

**Issue by granik** [manzinello/mailgo#62]
We implemented a [drupal-module](https://www.drupal.org/project/mailgo) for this library.
We'd like to allow users not to load module CSS, but also use their own styles. That would be great if your library loaded CSS separately from JavaScript. Thanks.

**Comment by manzinello** [comment]
Start working on this! I just want some help in configuring webpack to build and minify `src/mailgo.scss` in `dist/mailgo.css`

**Comment by granik** [comment]
> Start working on this! I just want some help in configuring webpack to build and minify `src/mailgo.scss` in `dist/mailgo.css`

Do you already have webpack config drafts for this? I'm not a frontend developer unfortunately.

**Comment by manzinello** [comment]
> Do you already have webpack config drafts for this? I'm not a frontend developer unfortunately.

No, I'm sorry. I know `webpack` but I have never worked with it to create a CSS from an SCSS (without JS). In the first releases of **mailgo** I was using both `webpack` and `gulp` to achieve this. Then I have removed gulp. I just want to wait some help from someone more expert then me about webpack, if it is not possible then I will re-introduce `gulp` or `grunt` to develop this part and close this issue.

**Comment by granik** [comment]
> No, I'm sorry. I know `webpack` but I have never worked with it to create a CSS from an SCSS (without JS). In the first releases of **mailgo** I was using both `webpack` and `gulp` to achieve this. Then I have removed gulp. I just want to wait some help from someone more expert then me about webpack, if it is not possible then I will re-introduce `gulp` or `grunt` to develop this part and close this issue.

Gulp will be OK, I think.

**Comment by manzinello** [comment]
Re-introduced gulp to export **CSS**. CSS will be available in the next mailgo release in `dist` folder.
