### ISSUE TITLE
Add Yahoo Mail to :mailto Options

### ISSUE THREAD

**Issue by puremana** [manzinello/mailgo#66]
Yahoo mail had a market share of [6.3%](https://www.litmus.com/blog/infographic-the-2019-email-client-market-share/) in 2019 and is supposedly rising in popularity. This is fairly close to Outlooks 9.1%.

I am not sure if this is possible with query params but it is atleast worth looking into in my opinion.

**Comment by manzinello** [comment]
Thank you for the data of Yahoo usage, it is a very interesting point. I have made some research and it seems that Yahoo supports query parameters for the email recipient, subject, etc...

Thank you for your suggestion, I think that add Yahoo mail is a very good idea.

**Comment by manzinello** [comment]
Working on this! This is the first proposal:

<img width="321" alt="Screenshot 2020-08-25 at 21 18 25" src="https://user-images.githubusercontent.com/5347132/91218159-f8587700-e718-11ea-93e1-6d25661440ae.png">
<img width="322" alt="Screenshot 2020-08-25 at 21 18 33" src="https://user-images.githubusercontent.com/5347132/91218165-f989a400-e718-11ea-99e6-fa577e715277.png">

I'm not sure when it will be available, I'm working on it.

**Comment by manzinello** [comment]
Available and tested, it will be present in the next mailgo release.
