### ISSUE TITLE
Lighthouse audit fail: Uncrawlable Links

### ISSUE THREAD

**Issue by shadow81627** [manzinello/mailgo#67]
I am not able to use mailgo due to lighthouse audit for link crawling failing. Are we able to change the href or use a different html element like a button or maybe use an onclick attribute?

Search engines may use `href` attributes on links to crawl websites. Ensure that the `href` attribute of anchor elements links to an appropriate destination, so more pages of the site can be discovered. Learn More: https://support.google.com/webmasters/answer/9112205

Uncrawlable Link
--
```
open in Gmail<a id="m-gmail" href="javascript:void(0);" class="m-open m-gmail">
open in Outlook<a id="m-outlook" href="javascript:void(0);" class="m-open m-outlook">
open default<a id="m-open" href="javascript:void(0);" class="m-open m-default">
copy<a id="m-copy" href="javascript:void(0);" class="m-copy w-500">
open in Telegram<a id="m-tg" href="javascript:void(0);" class="m-open m-tg" style="display: none;">
open in WhatsApp<a id="m-wa" href="javascript:void(0);" class="m-open m-wa">
open in Skype<a id="m-skype" href="javascript:void(0);" class="m-open m-skype">
call as default<a id="m-call" href="javascript:void(0);" class="m-open m-default">
copy<a id="m-tel-copy" href="javascript:void(0);" class="m-copy w-500">
```

**Comment by manzinello** [comment]
Thank you so much, really interesting point. I think that there are no problems if we set the `href` to a real destination and manage the click on the element with a simple `preventDefault()`. In this way I think that there will not be uncrawlable links. I will work on this, thank you. In the next release there will be the fix.

**Comment by manzinello** [comment]
I've worked on this, everything seems to work correctly.
I have to do more tests but I think that this change can be part of the next mailgo release, thank you again!

**Comment by manzinello** [comment]
The new `href` attributes for mailgo actions will be present in the next mailgo release!
