### ISSUE TITLE
auto translation ? Fr or fr-FR

### ISSUE THREAD

**Issue by 6clicks** [manzinello/mailgo#68]
If I understand well. the script is based on the attribute lang in the html to choose a language defined in the i18n.json. 
and I think it doesn't work in french with WordPress because by default the html tag for french is lang="fr-FR" .. and in the file it's only fr.. 

I don't know if am right ... any help to translate in french?

**Comment by manzinello** [comment]
The case of `lang="fr-FR"` is a very good point. Mailgo would be already be available in French (see the `i18n.json`), however the case of lang different from "fr" is not managed at the moment. We have to work on this!

To see the French translation you can clone the repo and open the `index.fr.html` in the `examples` folder.

With configuration you can already set a language to be forced (so no more `lang` attribute from `html` element), however for WordPress we are working on a "window.mailgoConfig" that can work (at the moment the configuration is available only for npm package) and possibly to set the values directly from the WordPress admin.

**Comment by manzinello** [comment]
I've implemented just now a really fast solution for this problem: https://github.com/manzinello/mailgo/commit/cffe354e35a3e1b66294c294fbadfecd33b8ed70.

There is a new `index.fr-FR.html` in `examples` folder with your case (https://github.com/manzinello/mailgo/commit/a1e780872f896238a55579dd9cd53172ce5fca82), it seems to work correctly now.

I have to test it in deep, if everything is ok it will be in the next **mailgo** release (and obviously in the next mailgo plugin for WordPress release).

**Comment by 6clicks** [comment]
Exellent ... it was fast ! it works like a charm ( I use WordPress but not the plugin ) .. I just update my mailgo.js.min at it's work .. thank U

**Comment by manzinello** [comment]
Perfect! I close this issue. I will make more tests for the changes I have made, but thank you again for the problem you have raised.
