### ISSUE TITLE
i18n missing string

### ISSUE THREAD

**Issue by theikid** [manzinello/mailgo#71]
When clicking on "copy" button the text switch to "copied" which has no i18n translation.

**Comment by manzinello** [comment]
You are completely right. I will work on this. Thank you so much.

**Comment by theikid** [comment]
Thanks. I also saw it switch back to non i18n"copy"  after it was copied

**Comment by manzinello** [comment]
Thank you, it's another bug. I'll open another issue for this, thank you.

**Comment by manzinello** [comment]
Opened also https://github.com/manzinello/mailgo/issues/72

**Comment by manzinello** [comment]
Fixed, everything will be in the next **mailgo** release, thank you so much. Now "copied" must be translated (at the moment "copied" is used but there is the possibility to translate it in `i18n.json`)

**Comment by theikid** [comment]
Thanks, can i help with the french translation somehow ?

**Comment by manzinello** [comment]
Sure! Submit directly a PR with "copied" translated in `i18n.json` file under **fr** attribute! Thank you!
