### ISSUE TITLE
Outlook link not working correctly

### ISSUE THREAD

**Issue by vanaf1979** [manzinello/mailgo#74]
If i click on the outlook link the browser opens this link https://outlook.live.com/owa/?path=/mail/action/compose&to=example%40example.com but i land on the outlook homepage. I can then login, but then i don't get any compose window.

If on the other hand i change the url to https://outlook.office365.com/owa/?path=/mail/action/compose&to=example%40example.com (Note the other domain name) i do get a compose window.

I'm not sure if it is platform dependent but I've noticed this issue on MacOs in Firefox with MailGo 0.9.16

**Comment by manzinello** [comment]
Thank you so much! I will make some tests. I am sure that I have changed the domain from `outlook.office365.com` to `outlook.live.com` a lot of time ago but maybe in the meanwhile something has changed. Thank you.

**Comment by manzinello** [comment]
I'm making some tests. It seems that Microsoft makes a redirect to `https://outlook.live.com/mail/0/deeplink/compose/` link. However, in my tests `outlook.live.com` works correctly, maybe you have a custom domain with Office365 or a simple `outlook.com` (or similar) email address? I think that the point is this one...

**Comment by manzinello** [comment]
Hi @vanaf1979, any update about this? Thank you.

**Comment by pcjmfranken** [comment]
The`outlook.live.com` link seems to work fine for consumer accounts (`@outlook.com`, `@live.com`, etc.), but only the `outlook.office365.com` link successfully opens a composition screen for my Office365 for Business account.

**Comment by manzinello** [comment]
You are right. In fact it is a really strange situation: we really don't know if the user is using a classic `@outlook.com` email address or an Office365 account. Really difficult to solve this at the moment, I have to study the situation more in deep, you have suggestions? A simple solution is add another button with `Outlook Office365` that opens the `outlook.office365.com`, I really don't like this... What do you think about?

**Comment by pcjmfranken** [comment]
I believe it greatly depends on the individual use case. On many sites/pages that are solely targeting either B2C or B2B visitors it might be fine to just use one or the other. I'm sure there are many mixed cases as well where a distinction between the two seems unavoidable.

Admittedly I'm not actually a user of this (very neat!) project. Just ended up here on my quest for an Office365-specific mailto solution.

Displaying two separate buttons looks to be the most straightforward solution, but that's a lot of screen real-estate for our friends at MS :)

**Comment by manzinello** [comment]
> I believe it greatly depends on the individual use case. On many sites/pages that are solely targeting either B2C or B2B visitors it might be fine to just use one or the other. I'm sure there are many mixed cases as well where a distinction between the two seems unavoidable.

I think you are right.

> Admittedly I'm not actually a user of this (very neat!) project. Just ended up here on my quest for an Office365-specific mailto solution.

No problem, I am just really open to suggestions.

> Displaying two separate buttons looks to be the most straightforward solution, but that's a lot of screen real-estate for our friends at MS :)

Well, I think that maybe I can solve this also with `MailgoConfig`. By default the modal will use `outlook.live.com`, with a configuration parameter can be chosen to override it with `outlook.office365.com` or to display also a different button with the Office365 possibility. In this case everyone choose what he/she wants. I have to think about it... I think that choose only one of them is wrong now and I don't know if there is a global solution for both.

**Comment by manzinello** [comment]
I have worked on this! The new `office365` config parameter will be in the next release!

**Comment by manzinello** [comment]
Relased mailgo 0.11.2 now with the new `office365` attribute in configuration, here the documentation: https://mailgo.dev/docs/configuration#office365.
I close this issue, if there is something else please open a new one!
