### ISSUE TITLE
Not working at all in any browser! (Gatsby)

### ISSUE THREAD

**Issue by tr1s** [manzinello/mailgo#83]
I installed the package, tried with and without dark mode, nothing. I click the mailto: link and nothing happens. No errors in the console either. Tried with Firefox, Chrome, Safari.

The moment I remove mailgo from the gatsby-config my normal matilto: links work again.

Anyone else?

**Comment by manzinello** [comment]
I've seen that you have opened an issue in **gatsby-plugin-mailgo** https://github.com/manzinello/gatsby-plugin-mailgo/issues/1. I close this at the moment and reply on gatsby-plugin-mailgo. Then if it is a problem with mailgo JS library we will re-open this, ok?

**Comment by tr1s** [comment]
Sounds good!
