### ISSUE TITLE
window is not defined in Gatsby

### ISSUE THREAD

**Issue by manzinello** [manzinello/mailgo#84]
From https://github.com/manzinello/gatsby-plugin-mailgo/issues/1#issuecomment-693801072 @AlexFernando

**Comment by AlexFernando** [comment]
Hi again @manzinello , thanks for your answer. 

1.- I tried the following code but I got the following error while trying to use gatsby build. You can check both in the pictures. 

![err_4](https://user-images.githubusercontent.com/9219348/93505861-f2fede80-f90a-11ea-95f8-71d78d93bb7f.png)
![mailgo_err3](https://user-images.githubusercontent.com/9219348/93505864-f4300b80-f90a-11ea-816b-5e9d7e9c43d9.png)
I just want to use mailgo in a styled component button like this: 
`<Button href="#mailgo" data-address="info" data-domain="3allez.com" >Notify Us</Button>`


2.- Also gatsby recommend this solution for third-party modules:
`exports.onCreateWebpackConfig = ({ stage, loaders, actions }) => {
  if (stage === "build-html") {
    actions.setWebpackConfig({
      module: {
        rules: [
          {
            test: /bad-module/,
            use: loaders.null(),
          },
        ],
      },
    })
  }
}`

But I tried to replace /bad-module/ for 'gatsby-plugin-mailgo' or 'mailgo.min.js', but no working. Probably I'm doing something wrong in both solutions. So let me know what you think. Thanks for your help.

**Comment by manzinello** [comment]
Hi @AlexFernando, I really want to help you to solve the problem. I take this opportunity maybe to be more clear in the docs about SSR, because in fact I have faced the problem just in Next.js.

Well, about your first screenshot everything seems to be ok, in the second screen I think that there is something wrong with React Hook usage, not in particular with **mailgo**. I have used that example with React Hooks in Next.js and I haven't any problem, here it seems that something with Hooks is not ok with the build process. I have found this https://stackoverflow.com/questions/56251774/invariant-violation-invalid-hook-call-error-on-deployment#:~:text=Uncaught%20Invariant%20Violation%3A%20Minified%20React,errors%20and%20additional%20helpful%20warnings.&text=Invalid%20hook%20call.,body%20of%20a%20function%20component, that seems to be the problems here we have.

Sorry, but I really don't know Gatsby SSR well, so with the second point I am really not useful. However, I think that there is a bit confusion about `mailgo` and `gatsby-plugin-mailgo`. You have added both as dependencies? Because to call `mailgo()` you must have `mailgo` in dependencies, the Gatsby plugin is the way to add very easily mailgo to Gatsby website and it requires obviously the edit of `gatsby-config`. The question is this one: haven't you followed the instructions for `gatsby-plugin-mailgo` (https://www.gatsbyjs.com/plugins/gatsby-plugin-mailgo/) that requires `gatsby-config`? Haven't you modified `gatsby-config`?  Do you want to have a particular installation of mailgo? Just to know and better understand the problem.

Thank you.

**Comment by AlexFernando** [comment]
Hi @manzinello , sorry for my late reply and also for taking your time. In the end, I didn't realize that  1- I only had to install gatsby-plugin-mailgo, 2.- add it to gatsby-config.js (which I did), and then just use it in my Button component. Instead, I did once more unnecessary step: 3.- `import "mailgo/dist/mailgo.min.js"`, and the problems started right here, when I deleted that, it worked, and no need of UseEffect() or initialize window. I didn't try to do the mailConfig, and still, I need to figure the mailgo() function with UseEffect() out, but with just steps 1 and 2 it worked in gatsby, but I'll try it next days and I'll let you know. Thanks for all your help.

**Comment by manzinello** [comment]
No problem! I leave you also here the link to repository **gatsby-mailgo-example** (https://github.com/manzinello/gatsby-mailgo-example) and its deploy (https://gatsby-mailgo-example.netlify.app), I have made it as an example of `gatsby-plugin-mailgo` with also a `mailgoConfig` (in particular the dark mode). I'm just happy that everything works now, maybe I will try to be more clear on the docs (and on the README of Gatsby plugin). I close this issue because it is solved, feel free to open a new one if you have some other problems with mailgo or just comment this one if everything is ok with the configuration!
