### ISSUE TITLE
Using Mailgo Dynamically

### ISSUE THREAD

**Issue by yoavaviram** [manzinello/mailgo#86]
How should I go about calling mailgo with a mailto link i'm generating dynamically?

Here's the code:
https://github.com/your-digital-rights/yourdigitalrights.org/blob/2d3cdffb3d76de478a83634124572f4e667489d8/src/components/PersonalInfoForm/index.js#L94

**Comment by manzinello** [comment]
A really really interesting point. At the moment **mailgo** works on clicks or interactions with elements in which there is a `mailto:` (or tel) link, but it not fires in case there is, like in the code you have posted, a `window.open([LINK MAILTO]);`. I think that I will work to cover also this case.

Sorry, but for its implementation mailgo is at the moment not able to intercept the `window.open` method but thank you so much for you example, I will surely work on this.

Maybe I can just export some method that can be called directly from mailgo in npm to do this, but I have to study it better.

**Comment by manzinello** [comment]
I am open to any type of idea to cover this very particular case. If you have some suggestions to make it better please let me know, you can also submit a PR referring to this ISSUE, thank you again.

**Comment by yoavaviram** [comment]
Thank you for the quick response! Exporting a method that can be called directly from mailgo would be grate for my use case. Sorry but I don't trust my JS skills enough to submit a PR... Anyway I'll be looking forward.

**Comment by manzinello** [comment]
No problem for the PR, I can work on this!
I think that export a method would be perfect (maybe also for other use cases), I will work on this, when I make changes I refer to this issue. Thank you again for the good point.

**Comment by manzinello** [comment]
Started working on this, I think that the method will be called `mailgoDirectRender` with a `string` parameter (the URL, mailto or tel) and the mailgo modal will appear after the call. I have to work and test this new way to render the modal.

**Comment by yoavaviram** [comment]
Amazing! Thank you for the amazing support. I'd love to support you back in some way. Let me know if there's a way to donate to the project.

**Comment by manzinello** [comment]
I have to work a lot on this but everything you have suggested will be in the next release. Something already works but I have to test it in deep. I am working on the **mailgo examples** repository, when something is ready I will post it a complete example (with webpack in this case): https://github.com/manzinello/mailgo-examples.

Mailgo has an **Open Collective** page: https://opencollective.com/mailgo, no one has donated yet but thank you so much if you want to contribute! Will be wonderful just if you want to help me spread mailgo to more users!

**Comment by yoavaviram** [comment]
Thanks, I've made a small contribution (sorry, we're a small nonprofit with a tiny budget). Once we have start using mailgo I'll give it credit on the website as one of our [sponsors](https://yourdigitalrights.org/about).

**Comment by yoavaviram** [comment]
Any idea when the next release will be out?

**Comment by manzinello** [comment]
Thank you so much, really! Today is also my birthday, so thank you again.

> Any idea when the next release will be out?

Next week I guess, I am making a lot of tests at the moment. When I release it I will write the release here (and maybe close the issue!).

**Comment by manzinello** [comment]
Just to keep you updated about the work, here the folder where you can see an example of **mailgo direct render** (of a `mailto` URI passed as a parameter of the new method `mailgoDirectRender`) when there is a clic on a button: https://github.com/manzinello/mailgo-examples/tree/master/example-direct.

Javascript file is this one: https://github.com/manzinello/mailgo-examples/blob/master/example-direct/src/index.js.

Here the example deployed: https://mailgo-examples.vercel.app/example-direct/. I am using **webpack** in this example.

**Comment by yoavaviram** [comment]
Happy belated birthday! I'll take a look at the examples.

**Comment by manzinello** [comment]
**Mailgo 0.10.0 released**! Here the initial docs for the new Direct Render: https://mailgo.dev/docs/direct-render.

`mailgoDirectRender` is also available as window function from mailgo 0.10.0 https://mailgo.dev/docs/window-functions.

I close this issue, if you have something else to suggest or any type of comment feel free to open a new one. If something is not working with `mailgoDirectRender` re-open this one!

Thank you.

**Comment by yoavaviram** [comment]
Thank you! I'll give it a go.
