### ISSUE TITLE
responsive setting

### ISSUE THREAD

**Issue by waldorfpatriot** [manzinello/mailgo#87]
My impression is, that ppl use their mail apps on desktop not as strong as on their mobile phones. So I would like to activate the plugin on desktop, but not on mobile or tablet. Is there a hack to do that? Would you be willing to implement a responsive setting?

**Comment by manzinello** [comment]
Interesting point. No hack at the moment to do this, but I can work on this. Well, I think that the best way to do this is to make it in JS taking the user agent, not just with the screen dimensions... What do you think about? Thank you for this suggestion.

**Comment by waldorfpatriot** [comment]
thank you for your rapid response! 
user agent is the cleanest solution, I agree.

**Comment by manzinello** [comment]
Added from mailgo `0.11.0`! Here the documentation: https://mailgo.dev/docs/responsive
