### ISSUE TITLE
Question: hide body and subject in modal

### ISSUE THREAD

**Issue by yoavaviram** [manzinello/mailgo#90]
Hi Matteo, 

Thanks for the direct render functionality. I just tested it and it works as I had hoped!

I've got one unrelated question. What would be the best way to hide the subject and body in the modal? In my case they are both quite lengthy and therefore it does not make sense to display them. 

Thanks,

Yoav

**Comment by manzinello** [comment]
Interesting suggestion. Maybe I can work on new attributes in MailgoConfig for this!

**Comment by yoavaviram** [comment]
That would be awesome!

**Comment by yoavaviram** [comment]
Hi @manzinello , have you made any progress on this one?

**Comment by manzinello** [comment]
Hi @yoavaviram, at the moment I am testing a new version of mailgo (`0.11.0`), that contains already a lot of changes.
After the release i will work on enhancements like this one, absolutely.

**Comment by manzinello** [comment]
I've worked on this! There will be the new `details` attribute in `configuration` where you will be able to show/hide elements of the details from the modal (cc, bcc, body and subject for emails, msg for tel).
I am working on this (and testing it), you can check it in `index.windowconfig.html` in examples removing the comment on cc (https://github.com/manzinello/mailgo/commit/2bce02bc5d716584c0ea723a45b7c1759a820382)

**Comment by yoavaviram** [comment]
Amazing,  when do you think it will be released?

**Comment by manzinello** [comment]
I will try to release a new mailgo version with these new features within the end of the week!
I will keep you updated about this directly in this issue.

**Comment by yoavaviram** [comment]
Thanks!

**Comment by manzinello** [comment]
Relased mailgo 0.11.2 now with the new `details` attribute in configuration, here the documentation: https://mailgo.dev/docs/configuration#details.
I close this issue, if there is something else please open a new one!

**Comment by yoavaviram** [comment]
Amazing!

We're now using mailgo in production (for example when you submit the form at the top of this [page](https://yourdigitalrights.org/d/facebook.com). I've also added you to our list of sponsors on our [about](https://yourdigitalrights.org/about/) page.

A few questions and comments:

1. It seems like the direct render option parses configuration in a different way to the normal initialization. While the 'details' attribute is supported 'dark' is not. 
2. Maybe related to number 1, passing a dictionary with configuration options to the direct renderer had no affect. I had to use window.mailgoConfig option. If this is the intended usage I suggest noting it in the documentation since it was not obvious to me. 
3. It would be great to be able to hide the 'to' field in addition to the others (subject, bcc, cc, body). In my use the user is about to review all of these fields in their email client so no reason to do it twice. 

Here is the code that's currently in production: https://github.com/your-digital-rights/yourdigitalrights.org/blob/master/src/components/PersonalInfoForm/index.js

Many thanks!

**Comment by manzinello** [comment]
Thank you so much for your comments! I will check it and maybe will open single issues for them. In particular the first 2 seems to be bugs, so I have obviously to check them in deep. If you want to open single issues for them feel free to to it, otherwise I will do it.
Have a great day,

**Comment by yoavaviram** [comment]
Another issue: clicking on 'copy' only copies the recipient's email address.

**Comment by yoavaviram** [comment]
Also, the subject line opens up as the "to" address in gmail. This makes the librafry unusable for us in the current state.

**Comment by yoavaviram** [comment]
I have opened issues for the relevant problems.
