### ISSUE TITLE
Doesn't work in links inside dynamically created elements

### ISSUE THREAD

**Issue by aquelfulano** [manzinello/mailgo#91]
Hi, and thanks for this tool. Very useful.

I'm discovering it just now, and I'm trying it in a new web I'm creating in Wordpress.
It works fine, but I've just found an issue, and in the documentation I didn't find the solution.

In my case, the issue arrives when I put a mailto link inside a dynamic created element. I mean an element that is not rendered in the very first page rendering but later by a jQuery event.

So, my question is if there is something that I can do by myself in the options to fix that, or maybe I have to touch the code.

Thanx for your response and for your work.

**Comment by manzinello** [comment]
Hi, thank you for your message! Well, mailgo actually not fires at a page load but it intercepts the clicks on possible `mailto` and `tel` links, so infact the case of a dynamical rendering of a mailto elements already should work (it works in SPAs where the routes are changed dynamically, for example), I think that something else is not working here maybe. I want to go deep in this problem: are you using the latest version of mailgo?

If you want an immediate solution I think that the `mailgoDirectRender` at the moment would solve (https://mailgo.dev/docs/direct-render see the real example https://mailgo.dev/docs/direct-render#real-example). However, in this case it is just a workaround! If it is a bug of mailgo I really want to fix it, is your website online? Or there is a repository with the code? Please give me some details, at the end of `DOMContentLoaded` the `mailgo` elements are added to the DOM?

Thank you.

**Comment by manzinello** [comment]
Any update about this @aquelfulano? Thank you.

**Comment by manzinello** [comment]
Closed due to inactivity, if you some updates please re-open this issue.
