### ISSUE TITLE
mailgo modal doesn't open when clicking on telephone like if you exclude a telephone action e.g. whatsapp using window.mailgoConfig

### ISSUE THREAD

**Issue by louiechristie** [manzinello/mailgo#93]
## Expected Behavior

mailgo modal opens when clicking on telephone like if you exclude a telephone action e.g. whatsapp using window.mailgoConfig

## Actual Behavior

mailgo modal doesn't open when clicking on telephone like if you exclude a telephone action e.g. whatsapp using window.mailgoConfig

## Steps to Reproduce the Problem

Add this to the head of a HTML file:

```html
<html>
  <head>
  <script>
    window.mailgoConfig = {
      showFooter: false,
      actions: {
        whatsapp: false,
      },
    };
  </script>
  <script src="https://unpkg.com/mailgo@0.11.1/dist/mailgo.min.js" defer></script>
  </head>
  <body>
    <a href="#mailgo" data-tel="+442079460000">
  </body>
</html>
```

## Workaround

Include ```tel: true,``` in window.mailgoConfig

```html
<html>
  <head>
  <script>
    window.mailgoConfig = {
      showFooter: false,
      tel: true,
      actions: {
        whatsapp: false,
      },
    };
  </script>
  <script src="https://unpkg.com/mailgo@0.11.1/dist/mailgo.min.js" defer></script>
  </head>
  <body>
    <a href="#mailgo" data-tel="+442079460000">
  </body>
</html>
```

## Specifications

  - Version: https://unpkg.com/mailgo@0.11.1/dist/mailgo.min.js
  - Platform: macOS 10.15.7
  - Browser: Firefox 82.0.3 (64-bit)

**Comment by louiechristie** [comment]
Fixed itself, either it's an intermittent issue or I made a mistake.

Test passing:
https://github.com/louiechristie/mailgo/blob/master/examples/index.windowconfig.html

**Comment by manzinello** [comment]
Hi @louiechristie, I will make anyway more tests with `tel` and `actions` attributes in head. In the example `index.windowconfig.html` I have used only the scripts added in the end of the body.
