### ISSUE TITLE
Subject line opens up in 'to' address in gmail / direct render

### ISSUE THREAD

**Issue by yoavaviram** [manzinello/mailgo#95]
I am the following configuration:
```
var window.mailgoConfig = {
  dark: true,
  details: {
    subject: false,
    body: false,
    to: false,
    cc: false,
    bcc: false,
  },
};
```

When an email is opened in Gmail the designated subject line text appears in the "to" field. I did not check in other configurations.

**Comment by manzinello** [comment]
I have to make more check on this, thank you for your issue!

**Comment by manzinello** [comment]
Everything seems to work correctly now (see the `index.directrender.html` under examples), am I missing something?

**Comment by yoavaviram** [comment]
I'm running with 11.3 and it seems fine so far, thanks!

**Comment by manzinello** [comment]
Perfect! I close this issue. If there is something else about this re-open it!
