### ISSUE TITLE
Dark theme is not supported with direct render.

### ISSUE THREAD

**Issue by yoavaviram** [manzinello/mailgo#97]
I am the following configuration:
```
var window.mailgoConfig = {
  dark: true,
  details: {
    subject: false,
    body: false,
    to: false,
    cc: false,
    bcc: false,
  },
};
```

However the dark theme option has no affect.

**Comment by manzinello** [comment]
I think that you have to use

```
window.mailgoConfig = {
  dark: true,
  details: {
    subject: false,
    body: false,
    to: false,
    cc: false,
    bcc: false,
  },
};
```

`window` is a global object, you have not to define it with `var`. Please, check this example (https://github.com/manzinello/mailgo/blob/master/examples/index.windowconfig.html). If something is not working let me know!

**Comment by manzinello** [comment]
Re-open this, you are right, also testing without `var` it is not working. Thank you. I have to work on this.

**Comment by manzinello** [comment]
I have already work on a solution for this. I have to test it and it will be in the next release. Thank you.

**Comment by yoavaviram** [comment]
Any idea when the next release is due?

Hope you have a happy new year!

**Comment by manzinello** [comment]
Happy new year!

I think I will release a new version of mailgo this week!

**Comment by manzinello** [comment]
I'm sorry, I am a bit in late with the release because I am also working on a completely new mailgo.dev (updated to Docusarus 2), I am working hard, I will try to release everything in this week.

**Comment by yoavaviram** [comment]
Happy new year! no worries, thanks for the effort.

**Comment by manzinello** [comment]
Fixed in the latest version of mailgo! If something is now working please re-open this issue!
